name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Release artifacts to GitHub
        run: |
          # Create powershell install zip
          pushd powershell/install
          zip -r ../../falcon_windows_install_scripts.zip *.ps1
          popd

          # Create a list of files to upload
          list_of_files=$(find . -type f \( -name "*.sh" -o -name "*.ps1" -o -name "*.zip" \))

          # Create sha256sums.txt
          for file in $list_of_files; do
            pushd $(dirname $file) > /dev/null
            sha256sum $(basename $file)
            popd > /dev/null
          done > sha256sums.txt

          # Upload the files to GitHub release
          gh release upload $TAG $list_of_files sha256sums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name }}

